wallpaper {
    monitor = eDP-1
    path = /home/kopihue/Pictures/wallpapers/plain-gruvbox-light.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/kopihue/Pictures/wallpapers/plain-gruvbox-light.png
    fit_mode = cover
}

splash = false
