wallpaper {
    monitor = eDP-1
    path = /home/kopihue/Pictures/wallpapers/gruvbox-dark-box.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/kopihue/Pictures/wallpapers/gruvbox-dark-box.jpg
    fit_mode = cover
}

splash = false
